### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by torkildson** [BarquistLab/sCIRCLE#5]
There is no .exe file that I could find in the un zipped folder. I searched the folder using *.exe and there were no results.

Thank you for creating this, I look forward to using it.

T

**Comment by lbarquist** [comment]
Hi,

I just downloaded the archive (https://github.com/BarquistLab/sCIRCLE/releases/download/v0.1.2-alpha/sCircle_v.0.1.2-alpha.zip) and there is a sCIRCLE.exe in the sCIRCLE directory. It looks like there's a shortcut to it in the root directory of the zip file as well, but I don't have a Windows machine to test it at the moment. Hope this helps!

-Lars
